version: "3"

services:
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: '--appendonly yes'

  mongodb:
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - pg-data:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
#      MYSQL_PASSWORD: password
#      MYSQL_USER: root
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./web:/home/user/www/project/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/run/php/php7.4-fpm.sock:/var/run/php/php7.4-fpm.sock

  apache:
    image: httpd:2.4.43
    ports:
      - 88:88
    volumes:
      - ./docker/apache:/usr/local/apache2/htdocs
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

volumes:
  redis-data:
  mongo-data:
  pg-data:
  mysql-data: