version: "3"

services:
  redis:
    image: redis:4.0.9
    volumes:
      - redis-data:/data
    command: '--appendonly yes'

  mongodb:
    image: mongo:3.6.3
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:10.12
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - pg-data:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
#      MYSQL_PASSWORD: password
#      MYSQL_USER: root
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: smersh/docker-course:nginx
    ports:
      - 80:80

  apache:
    image: smersh/docker-course:apache
    ports:
      - 88:80

  php:
    image: smersh/docker-course:php
    volumes:
      - runtime:/var/www/app/runtime

volumes:
  redis-data:
  mongo-data:
  pg-data:
  mysql-data:
  runtime: