version: "3"

services:
  redis:
    image: redis:4.0.9
    volumes:
      - redis-data:/data
    command: '--appendonly yes'

  mongodb:
    image: mongo:3.6.3
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:10.12
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - pg-data:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
#      MYSQL_PASSWORD: password
#      MYSQL_USER: root
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/app/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  apache:
    image: httpd:2.4.43
    ports:
      - 88:80
    volumes:
      - ./web:/var/www/app/web
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    user: "1000:1000"


volumes:
  redis-data:
  mongo-data:
  pg-data:
  mysql-data: