version: "3"

services:
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: '--appendonly yes'
  mongodb:
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
#    command: '--appendonly yes'


volumes:
  redis-data:
  mongo-data: